### ISSUE TITLE
setting up planetary-social docker repository

### ISSUE THREAD

**Issue by rabble** [planetary-social/ansible-scripts#14]
So we're hosting our own docker repos

**Comment by mplorentz** [comment]
@cooldracula suggested a tagging scheme for this where:
- every build is tagged with its commit hash and date
- the latest build is tagged `latest`
- there is a `stable` tag that we manually change after a build has undergone QA and is ready to go to production
- the production ansible scripts will use ansible-pull to update themselves when the stable tag changes.

@cooldracula did I get that right? Is this the right ticket for setting this up?

**Comment by cooldracula** [comment]
Basically, yah!  To elaborate: every docker image can have multiple image tags.  And so for any push to a branch of these repos, including main, we'd automatically make a new docker image with two tags:
- image:date+repo
- image:latest
And our test servers will continually pull and deploy the image with the `latest` tag for us to validate and such.

Then, if we do a tagged commit on main, following whatever sort of tagging structure we want (e.g. semver or date or dragonlance novels), we'd automatically make a new docker image with these tags:
- image:date+repo
- image:latest
- image:stable
- image:git_tag

Our production servers would automatically deploy the latest `stable` tag.

The main thing i wanted to clarify is that on github we wouldn't be tagging releases as stable, that'd just be a convention on the docker side.  This way, we can see and move through the progression of tagged releases in git, and revert `stable` to an earlier git tag if we need to.  This also means our server have an easy pattern for automatic deployment, while we keep the flexibility to deploy a particular image to a particular server if we need to. 

[infrastructure ticket #6](https://github.com/planetary-social/infrastructure/issues/6#issuecomment-1362979341), might be a better place for this, as I think you may be right that ghcr would be a better registry for doing this.

**Comment by cooldracula** [comment]
we host our images on github's container registry, ghcr, as it is easy to build as part of a github action, easy to find, and free.
