### ISSUE TITLE
setup script for deploying current version of the code for testing

### ISSUE THREAD

**Issue by rabble** [planetary-social/ansible-scripts#15]
Docs for running testing 'in production' on servers rather than just locally. This can be docs first and code second.

**Comment by mplorentz** [comment]
@cooldracula is the the ticket you are doing ansible-pull work for? 

I just wanted to document as we discussed today that part of that work is creating a `staging` branch in the three repos that make up the web viewer, and moving to more formal release scheme so we can make sure that we deploy compatible versions of everything to production. Maybe you can write up the more detailed plan on this ticket or wherever it is appropriate.

**Comment by cooldracula** [comment]
@mplorentz . I think this ticket works!  The ansible-pull work is a bit diffuse as it is a mix of process and code.  

I wrote up and shared a notion doc with an RFC for deployment strategies.  It felt easier to comment and iterate in there, but lemme know if you prefer a different place!
