### ISSUE TITLE
Nginx config for /follow/feedId route

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/ansible-scripts#19]
I added a new route to the Vue router `/follow/{feedId}` which behaves similar to the `/profile/{feedId}` route, except it redirects it to an external ssb-uri.

So I think this just needs to add a `/` to the route. This was a quick fix I did yesterday to reduce the complexity of the QR code you can scan to follow someone. Temporary until Planetary supports more ssb-uri types

**Comment by cooldracula** [comment]
@chereseeriepa , I was working on this this evening, but realized I wasn't quite sure what success should look like.  I added the route to the nginx config on my test server(ansible.fun) using the same logic as /profile/@feedid

at the moment the profile links should load successfully:
https://ansible.fun/profile/@nWjamqvbDIMIgZQchHCZPnROk0jUvjCO7oLLKdHgbJs=.ed25519

the follow link, for me, redirects to the frontend homepage.  This is telling me that nginx is sending the traffic to the frontend successfully, but i am not sure what it should do from there:

https://ansible.fun/follow/@nWjamqvbDIMIgZQchHCZPnROk0jUvjCO7oLLKdHgbJs=.ed25519

(for comparison, the planetary.pro config has not been updated, so follow routes redirect to the room-frontend, as it's the catchall for any unknown routes:
https://planetary.pro/follow/@UsApPEhMpZaoRzoT6PfWcBct5vOaHXntpndwAbTw3po=.ed25519)

What should I expect to see when I go to a /follow/@feedid route?

Thank you!

**Comment by mplorentz** [comment]
@martindsq can you verify that this type of link works in the Planetary app?

**Comment by cooldracula** [comment]
As this project is shelved, i am going to close this ticket.
