### ISSUE TITLE
Enable gift wrap kind for relay playbook

### ISSUE THREAD

**Issue by dcadenas** [planetary-social/ansible-scripts#88]
This is a small PR that would be great to have https://github.com/planetary-social/ansible-scripts/pull/87
I accidentally included the subdomain rule fix but I think it's not worth to undo it knowing that you are leaving soon @cooldracula

**Comment by cooldracula** [comment]
that PR looks good!  I merged it and deployed the updated changes to relay.nos.social and relay-dev.ansible.fun
